### ISSUE TITLE
Encode URI for links that include usernames

### ISSUE THREAD

**Issue by Illuminati4Life** [Illuminati4Life/vys-bot-framework#2]

**Comment by Illuminati4Life** [comment]
This can be seen in usernames where the user has a space. Example
![image](https://user-images.githubusercontent.com/14879958/42717240-7f7e3502-86b4-11e8-98ad-2101afe099db.png)

**Comment by prixyn** [comment]
replace spaces with `%20`

**Comment by Illuminati4Life** [comment]
im gonna do that lmao it's i forgot to put encodeuricomponent in

**Comment by Illuminati4Life** [comment]
i just realized why is this an issue
